/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./components/AppShell.vue')['default']
    CommandPalette: typeof import('./components/CommandPalette.vue')['default']
    KeyValueEditor: typeof import('./components/KeyValueEditor.vue')['default']
    KpiCard: typeof import('./components/KpiCard.vue')['default']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    RequestEditor: typeof import('./components/RequestEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
